DROP SEQUENCE SEQ_BPM_WORKITEM;
DROP SEQUENCE SEQ_BPM_PROCDEF;
DROP SEQUENCE SEQ_BPM_PROCDEFVER;
DROP SEQUENCE SEQ_BPM_PROCINST;
DROP SEQUENCE SEQ_BPM_PROCVAR;
DROP SEQUENCE SEQ_BPM_ROLEMAPPING;
DROP SEQUENCE SEQ_BPM_ACLTABLE;
DROP SEQUENCE SEQ_DOC_COMMENTS;

CREATE SEQUENCE SEQ_BPM_WORKITEM;
CREATE SEQUENCE SEQ_BPM_PROCDEF;
CREATE SEQUENCE SEQ_BPM_PROCDEFVER;
CREATE SEQUENCE SEQ_BPM_PROCINST;
CREATE SEQUENCE SEQ_BPM_PROCVAR;
CREATE SEQUENCE SEQ_BPM_ROLEMAPPING;
CREATE SEQUENCE SEQ_BPM_ACLTABLE;
CREATE SEQUENCE SEQ_DOC_COMMENTS;

-----------------/ SYSTEM TABLES /--------------------

DROP TABLE BPM_ERR_CODE;
CREATE TABLE BPM_ERR_CODE (
	"ERRORCODE" NUMBER,
	"MESSAGE_KO" VARCHAR2(2000 BYTE), 
	"MESSAGES_EN" VARCHAR2(2000 BYTE), 
CONSTRAINT PK_BPM_ERR_CODE
  PRIMARY KEY ( ERRORCODE )
);
INSERT INTO BPM_ERR_CODE (ERRORCODE, MESSAGE_KO, MESSAGES_EN) VALUES (0, '처리에 성공하였습니다.', 'Operation is success.');
INSERT INTO BPM_ERR_CODE (ERRORCODE, MESSAGE_KO, MESSAGES_EN) VALUES (101, '프로세스코드가 누락되었습니다.', 'Process code entry is missing.');
INSERT INTO BPM_ERR_CODE (ERRORCODE, MESSAGE_KO, MESSAGES_EN) VALUES (102, '신청서 번호가 누락되었습니다.', 'Biz key entry is missing.');
INSERT INTO BPM_ERR_CODE (ERRORCODE, MESSAGE_KO, MESSAGES_EN) VALUES (103, '액티비티코드가 누락되었습니다.', 'Activity code entry is missing.');
INSERT INTO BPM_ERR_CODE (ERRORCODE, MESSAGE_KO, MESSAGES_EN) VALUES (104, '수행코드가 누락되었습니다.', 'Action code entry is missing.');
INSERT INTO BPM_ERR_CODE (ERRORCODE, MESSAGE_KO, MESSAGES_EN) VALUES (105, '처리자 아이디가 누락되었습니다.', 'Operator id entry is missing.');
INSERT INTO BPM_ERR_CODE (ERRORCODE, MESSAGE_KO, MESSAGES_EN) VALUES (106, '위임자 아이디가 누락되었습니다.', 'Delegater id entry is missing.');
INSERT INTO BPM_ERR_CODE (ERRORCODE, MESSAGE_KO, MESSAGES_EN) VALUES (107, '해당 업무가 존재하지 않습니다.', 'Instance id is null.');
INSERT INTO BPM_ERR_CODE (ERRORCODE, MESSAGE_KO, MESSAGES_EN) VALUES (108, '권한이 없거나 처리 불가한 상태입니다.', 'No authority or completed activity.');
INSERT INTO BPM_ERR_CODE (ERRORCODE, MESSAGE_KO, MESSAGES_EN) VALUES (999, '시스템 오류입니다.', 'System error.');

DROP TABLE BPM_PROCDEF;
CREATE TABLE BPM_PROCDEF(
	"DEFID" NUMBER(19,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"PARENTFOLDER" NUMBER(19,0), 
	"ISFOLDER" NUMBER(1,0) DEFAULT 0, 
	"ISADHOC" NUMBER(1,0) DEFAULT 0, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"PRODVERID" NUMBER(19,0), 
	"PRODVER" NUMBER(10,0) DEFAULT 0, 
	"NAME" VARCHAR2(255 BYTE), 
	"MODDATE" DATE, 
	"OBJTYPE" VARCHAR2(10 BYTE), 
	"ALIAS" VARCHAR2(100 BYTE), 
	"ISVISIBLE" NUMBER(1,0) DEFAULT 1, 
	"COMCODE" VARCHAR2(20 BYTE),
CONSTRAINT PK_BPM_PROCDEF
  PRIMARY KEY ( defid )
);


DROP TABLE BPM_PROCDEFVER;
CREATE TABLE BPM_PROCDEFVER(
	"DEFVERID" NUMBER(19,0), 
	"FILEPATH" VARCHAR2(255 BYTE), 
	"VER" NUMBER(5,0), 
	"DEFID" NUMBER(19,0), 
	"DEFNAME" VARCHAR2(255 BYTE), 
	"MODDATE" DATE, 
	"PRODSTARTDATE" DATE, 
	"ISDELETED" NUMBER(1,0), 
	"PROGRAMID" VARCHAR2(100 BYTE), 
	"AUTHOR" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"DEFINITION" CLOB, 
	"CACHEDDEFINITION" BLOB,
  CONSTRAINT PK_BPM_PROCDEFVER
  PRIMARY KEY ( DEFVERID )
);

DROP TABLE BPM_PROCINST;
CREATE TABLE BPM_PROCINST (
      "INSTID" NUMBER(19,0), 
	"DEFVERID" NUMBER(19,0), 
	"DEFID" NUMBER(19,0), 
	"DEFNAME" VARCHAR2(255 BYTE), 
	"DEFPATH" VARCHAR2(255 BYTE), 
	"DEFMODDATE" DATE, 
	"STARTEDDATE" DATE, 
	"FINISHEDDATE" DATE, 
	"DUEDATE" DATE, 
	"STATUS" VARCHAR2(20 BYTE), 
	"INFO" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"ISADHOC" NUMBER(1,0) DEFAULT 0, 
	"ISARCHIVE" NUMBER(1,0) DEFAULT 0, 
	"ISSUBPROCESS" NUMBER(1,0) DEFAULT 0, 
	"ISEVENTHANDLER" NUMBER(1,0) DEFAULT 0, 
	"ROOTINSTID" NUMBER(19,0), 
	"MAININSTID" NUMBER(19,0), 
	"MAINDEFVERID" NUMBER(19,0), 
	"MAINACTTRCTAG" VARCHAR2(20 BYTE), 
	"MAINEXECSCOPE" VARCHAR2(20 BYTE), 
	"ABSTRCPATH" VARCHAR2(200 BYTE), 
	"DONTRETURN" NUMBER(1,0), 
	"MODDATE" DATE, 
	"EXT1" VARCHAR2(100 BYTE), 
	"INITEP" VARCHAR2(100 BYTE), 
	"INITRSNM" VARCHAR2(100 BYTE), 
	"CURREP" VARCHAR2(100 BYTE), 
	"CURRRSNM" VARCHAR2(100 BYTE), 
	"INITTASKID" VARCHAR2(100 BYTE), 
	"CURRSTATUSCODES" VARCHAR2(100 BYTE), 
	"CURRSTATUSNAMES" VARCHAR2(200 BYTE), 
	"DEFINITION" CLOB, 
	"VARIABLES" CLOB,
  CONSTRAINT PK_BPM_PROCINST
  PRIMARY KEY ( instid )
);

DROP TABLE BPM_PROCVAR;
CREATE TABLE BPM_PROCVAR (
	"VARID" NUMBER(19,0), 
	"INSTID" NUMBER(19,0), 
	"DATATYPE" NUMBER(2,0), 
	"VALUESTRING" VARCHAR2(4000 BYTE), 
	"VALUELONG" NUMBER(19,0), 
	"VALUEBOOLEAN" NUMBER(1,0), 
	"VALUEDATE" DATE, 
	"VARINDEX" NUMBER(3,0), 
	"TRCTAG" VARCHAR2(20 BYTE), 
	"ISPROPERTY" NUMBER(1,0), 
	"MODDATE" DATE, 
	"KEYNAME" VARCHAR2(50 BYTE), 
	"KEYSTRING" VARCHAR2(200 BYTE),
  CONSTRAINT PK_BPM_PROCVAR
  PRIMARY KEY ( varID )
);

DROP TABLE BPM_RoleMapping;
CREATE TABLE BPM_RoleMapping (
	"ROLEMAPPINGID" NUMBER(19,0), 
	"INSTID" NUMBER(19,0), 
	"ROOTINSTID" NUMBER(19,0), 
	"ROLENAME" VARCHAR2(20 BYTE), 
	"ENDPOINT" VARCHAR2(255 BYTE), 
	"VALUE" VARCHAR2(4000 BYTE), 
	"RESNAME" VARCHAR2(200 BYTE), 
	"ASSIGNTYPE" NUMBER(2,0), 
	"ASSIGNPARAM1" VARCHAR2(100 BYTE), 
	"DISPATCHOPTION" NUMBER(2,0), 
	"DISPATCHPARAM1" VARCHAR2(100 BYTE), 
	"GROUPID" VARCHAR2(30 BYTE),
  CONSTRAINT PK_BPM_ROLEMAPPING
  PRIMARY KEY ( ROLEMAPPINGID )
);

DROP TABLE BPM_WORKLIST;
CREATE TABLE BPM_WORKLIST(
  "TASKID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"ENDPOINT" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(100 BYTE), 
	"PRIORITY" NUMBER, 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"DUEDATE" DATE, 
	"SAVEDATE" DATE, 
	"INSTID" NUMBER(19,0), 
	"DEFID" NUMBER(19,0), 
	"DEFNAME" VARCHAR2(200 BYTE), 
	"TRCTAG" VARCHAR2(100 BYTE), 
	"TOOL" VARCHAR2(200 BYTE), 
	"PARAMETER" VARCHAR2(4000 BYTE), 
	"GROUPID" NUMBER, 
	"GROUPNAME" NUMBER, 
	"EXT1" VARCHAR2(200 BYTE), 
	"EXT2" VARCHAR2(200 BYTE), 
	"EXT3" VARCHAR2(200 BYTE), 
	"EXT4" VARCHAR2(200 BYTE), 
	"EXT5" VARCHAR2(200 BYTE), 
	"EXT6" VARCHAR2(200 BYTE), 
	"EXT7" VARCHAR2(200 BYTE), 
	"EXT8" VARCHAR2(200 BYTE), 
	"EXT9" VARCHAR2(200 BYTE), 
	"EXT10" VARCHAR2(200 BYTE), 
	"ISURGENT" NUMBER(1,0), 
	"HASATTACHFILE" NUMBER(1,0), 
	"HASCOMMENT" NUMBER(1,0), 
	"DOCUMENTCATEGORY" VARCHAR2(200 BYTE), 
	"ISDELETED" NUMBER(1,0), 
	"ROOTINSTID" NUMBER(19,0), 
	"DISPATCHOPTION" NUMBER(2,0), 
	"DISPATCHPARAM1" VARCHAR2(100 BYTE), 
	"ROLENAME" VARCHAR2(100 BYTE), 
	"RESNAME" VARCHAR2(100 BYTE), 
	"REFROLENAME" VARCHAR2(100 BYTE), 
	"EXECSCOPE" VARCHAR2(5 BYTE),
  CONSTRAINT PK_WORKLIST
  PRIMARY KEY ( TASKID )
);

create index idx_bpm_procvar on bpm_procvar(KEYSTRING);
create index idx_bpm_procvarinst on bpm_procvar(INSTID);
create index idx_bpm_rolemapping on bpm_roleMapping(roleName);

-----------------/ OLAP StarSchema /---------------------
DROP TABLE BPM_RSRC_DIM;
CREATE TABLE BPM_RSRC_DIM(
  "RSRC_ID" VARCHAR2(20 BYTE), 
	"RSRC_NAME" VARCHAR2(100 BYTE), 
	"DEPT_NAME" VARCHAR2(100 BYTE), 
	"DEPT_ID" VARCHAR2(20 BYTE), 
	"PSTN_NAME" VARCHAR2(50 BYTE), 
	"PSTN_ID" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"GENDER" NUMBER(1,0), 
	"BIRTHDAY" NUMBER(4,0),
  CONSTRAINT PK_BPM_RSRC_DIM
  PRIMARY KEY ( RSRC_ID )
);

DROP TABLE BPM_TIME_DIM;
CREATE TABLE BPM_TIME_DIM(
  "TIME_ID" NUMBER(11,0), 
	"YR" NUMBER(4,0), 
	"MNTH" NUMBER(2,0), 
	"QUTR" NUMBER(1,0), 
	"DAY" NUMBER(2,0), 
	"MODDATE" DATE,
  CONSTRAINT PK_BPM_TIME_DIM
  PRIMARY KEY ( TIME_ID )
);

DROP TABLE BPM_PRFM_FACT_2006;
CREATE TABLE BPM_PRFM_FACT_2006(
  "INST_ID" NUMBER(11,0), 
	"ROOTINST_ID" NUMBER(11,0), 
	"RSRC_ID" VARCHAR2(50 BYTE), 
	"TIME_ID" NUMBER(11,0), 
	"ACT_ID" VARCHAR2(100 BYTE), 
	"ACT_NAME" VARCHAR2(100 BYTE), 
	"DEF_ID" NUMBER(11,0), 
	"DEF_NAME" VARCHAR2(200 BYTE), 
	"PRSNGTIME" NUMBER(11,0), 
	"TRNRNDTIME" NUMBER(11,0), 
	"IDLETIME" NUMBER(11,0), 
	"CHOVRTIME" NUMBER(11,0), 
	"SSPNDTIME" NUMBER(11,0), 
	"COST" NUMBER(11,0), 
	"SLA_STFTRY" NUMBER(11,0), 
	"DEADLNHT" NUMBER(2,0), 
	"MODTIME" DATE
 );
 
DROP TABLE BPM_DEADLN_DIM;
CREATE TABLE BPM_DEADLN_DIM(
  "DEADLN_ID" NUMBER(2,0), 
  "DEADLN_DESC" VARCHAR2(255 BYTE),
  CONSTRAINT PK_BPM_DEADLN_DIM
  PRIMARY KEY ( DEADLN_ID )
);

-----------/ EXAMPLE ORGANIZATION CHART: Only for standalone version /-------------

DROP TABLE EMPTABLE;
create table EMPTABLE (
 "EMPNAME" VARCHAR2(100 BYTE), 
	"EMPCODE" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(64 BYTE), 
	"ISADMIN" NUMBER, 
	"JIKNAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PARTCODE" VARCHAR2(20 BYTE), 
	"GLOBALCOM" VARCHAR2(20 BYTE), 
	"LOCALE" VARCHAR2(10 BYTE) DEFAULT 'en', 
	"NATEON" VARCHAR2(50 BYTE), 
	"MSN" VARCHAR2(50 BYTE), 
	"MOBILENO" VARCHAR2(20 BYTE), 
	"MOBILECMP" VARCHAR2(5 BYTE), 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
 CONSTRAINT PK_emptable
  PRIMARY KEY ( empcode )
);

DROP TABLE PARTTABLE;
CREATE TABLE PARTTABLE (
  "GLOBALCOM" VARCHAR2(20 BYTE), 
	"PARTCODE" VARCHAR2(20 BYTE), 
	"PARTNAME" VARCHAR2(30 BYTE), 
	"PARENT_PARTCODE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
   CONSTRAINT PK_PARTTABLE
  PRIMARY KEY ( PARTCODE )
);

DROP TABLE ROLETABLE;
CREATE TABLE ROLETABLE (
 "ROLECODE" VARCHAR2(20 BYTE), 
 "COMCODE" VARCHAR2(20 BYTE), 
 "DESCR" VARCHAR2(225 BYTE), 
 "ISDELETED" NUMBER(1,0) DEFAULT 0, 
  CONSTRAINT PK_ROLETABLE
  PRIMARY KEY ( rolecode )
);

DROP TABLE ROLEUSERTABLE;
CREATE TABLE ROLEUSERTABLE (
  "ROLECODE" VARCHAR2(20 BYTE) NOT NULL, 
	"EMPCODE" VARCHAR2(20 BYTE) NOT NULL,
  CONSTRAINT PK_GROUPUSERTABLE
    PRIMARY KEY (roleCode, empCode)
);

Insert into EMPTABLE (EMPNAME,EMPCODE,PASSWORD,ISADMIN,JIKNAME,EMAIL,PARTCODE,GLOBALCOM,LOCALE,NATEON,MSN,MOBILENO,MOBILECMP,ISDELETED) values ('Tester','test','9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',1,null,null,'DEV','uEngine','en',null,null,null,null,0);
Insert into EMPTABLE (EMPNAME,EMPCODE,PASSWORD,ISADMIN,JIKNAME,EMAIL,PARTCODE,GLOBALCOM,LOCALE,NATEON,MSN,MOBILENO,MOBILECMP,ISDELETED) values ('Tester_ko','test_ko','9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',1,null,null,'DEV','uEngine','ko',null,null,null,null,0);
Insert into EMPTABLE (EMPNAME,EMPCODE,PASSWORD,ISADMIN,JIKNAME,EMAIL,PARTCODE,GLOBALCOM,LOCALE,NATEON,MSN,MOBILENO,MOBILECMP,ISDELETED) values ('employee','user_ko','9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',0,null,null,'DEV','uEngine','ko',null,null,null,null,0);
Insert into PARTTABLE (GLOBALCOM,PARTCODE,PARTNAME,PARENT_PARTCODE,DESCRIPTION,ISDELETED) values ('uEngine','DEV','Development',null,null,0);
Insert into ROLETABLE (ROLECODE,COMCODE,DESCR) values ('TM','uEngine','Trouble Manager');
Insert into ROLEUSERTABLE (ROLECODE,EMPCODE) values ('TM','test');

--- ApprovalLineActivity --------------------------------------

DROP TABLE DOC_COMMENTS;
CREATE TABLE DOC_COMMENTS(  
  "ID" NUMBER(*,0), 
	"INSTANCE_ID" NUMBER(*,0), 
	"CONTENTS" VARCHAR2(3000 BYTE), 
	"OPT_TYPE" VARCHAR2(100 BYTE), 
	"EMPNO" VARCHAR2(20 BYTE), 
	"EMPNAME" VARCHAR2(100 BYTE), 
	"EMPTITLE" VARCHAR2(100 BYTE), 
	"TRACINGTAG" VARCHAR2(10 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"UPDATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(20 BYTE), 
	"APPRTITLE" VARCHAR2(100 BYTE),
  CONSTRAINT DOC_COMMENTS
  PRIMARY KEY ( ID )
);

DROP TABLE COMTABLE;
CREATE TABLE COMTABLE (
	"COMCODE" VARCHAR2(20 BYTE), 
	"COMNAME" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	CONSTRAINT PK_COMTABLE
	PRIMARY KEY ( COMCODE )
);
insert into COMTABLE (COMCODE, COMNAME) values ('uEngine', 'UENGINE');

DROP TABLE BPM_ACLTABLE;
CREATE TABLE BPM_ACLTABLE (
	"ACLTABLEID" NUMBER(*,0), 
	"DEFID" NUMBER(*,0), 
	"COMCODE" VARCHAR2(20 BYTE), 
	"PARTCODE" VARCHAR2(20 BYTE), 
	"EMPCODE" VARCHAR2(20 BYTE), 
	"ROLECODE" VARCHAR2(20 BYTE), 
	"DEFAULTUSER" CHAR(1 BYTE), 
	"PERMISSION" CHAR(1 BYTE),
	CONSTRAINT PK_BPM_ACLTABLE
	PRIMARY KEY ( ACLTABLEID )
);

update bpm_procdef set OBJTYPE='folder' where ISFOLDER=1;
update bpm_procdef set OBJTYPE='process' where OBJTYPE is NULL;

DROP TABLE SCHEDULE_TABLE;
CREATE TABLE SCHEDULE_TABLE
(
    "SCHE_IDX" NUMBER(*,0), 
	"INSTID" NUMBER(*,0), 
	"TRCTAG" VARCHAR2(100 BYTE), 
	"STARTDATE" TIMESTAMP (6)
)
;

---------------2011.03.07. TAG
DROP SEQUENCE SEQ_BPM_TAG;
CREATE SEQUENCE SEQ_BPM_TAG;

DROP TABLE BPM_TAG;
CREATE TABLE BPM_TAG(
"TAGID" NUMBER, 
"NAME" VARCHAR2(255 BYTE), 
"COMCODE" VARCHAR2(20 BYTE),
CONSTRAINT PK_BPM_TAG PRIMARY KEY (TAGID)
);

DROP TABLE BPM_TAGMAPPING;
CREATE TABLE BPM_TAGMAPPING(
"TAGID" NUMBER, 
"INSTID" NUMBER(19,0), 
"ROOTINSTID" NUMBER(19,0)
);